apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/hsudbrock/talos-on-hetzner.git'
    targetRevision: main
    path: argo-app-of-apps/cert-manager-issuers
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: